<a href="https://colab.research.google.com/github/fareehazanib/ITAI_ML_FirstRepo_Zanib/blob/main/Zanib_Lab_02__Colab_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Module 02 Lab Exercise: Machine LearningTools**

**Learning Objectives**
- By the end of this lab, you will be able to:

1. Set up and navigate Jupyter Notebook, Google Colab, and VS Code environment.
2. Install and import essential Python libraries for machine learning.
3. Create and format professional documentation using Markdown or text.
4. Understand the basic workflow of data science tools

**Prerequisites**
1. Basic understanding of what machine learning is (Module 01)
2. Access to the internet for downloading tools and datasets
3. Working with google colab using your account or HCC acount.

**Part 1: Environment Setup and Tool Overview**

**Google Colab:** Interactive computing environments where you can write code, see results immediately, and document your work with text and visualizations.

**Python Libraries:** Pre-written code packages that make machine learning tasks easier:

NumPy (for Numerical Python): Created in 2005, for mathematical operations on arrays of numbers.
Pandas: Created in 2008, for manipulating data (like Excel, but more powerful). Pandas handles both homogeneous and heterogeneous data types.
Matplotlib: Data visualization library for creating charts and graphs.
Seaborn: Data visualization library for creating charts and graphs, but Seaborn is more interactive than matplotlib.
Scikit-learn: The main library for machine learning algorithms.
**Environment Setup Instructions:**

**Option 1:** Google Colab (Recommended for Beginners)

Go to colab.research.google.com
Sign in with your Google account
Click "New Notebook"
You're ready to go! Libraries are pre-installed.
**Option 2:** Jupyter Notebook

Look up for Anaconda Jupyter Notebook
Download the file for Jupyter Notebook based on the OS that you have
Run jupyter notebook
Create a new notebook
**Option 3:** VS Code

Download VS Code from code.visualstudio.com
Install Python extension
Install Jupyter extension
Create a new .ipynb file
For this lab, we recommend starting with Google Colab as it requires no installation. Colab is a browser-based platform.

**Part 2: Importing Libraries**

In [1]:
# general libraries
import numpy as np # np is an alias name for numpy
import pandas as pd # pd is an alias name for pandas
import os # for different operating system
import math # for mathematical operations

# data visualization libraries
import matplotlib.pyplot as plt # plt is an alias name for matplotlib
import seaborn as sns # sns is an alias name for seaborn

# machine learning libraries
import sklearn # for machine learning
from sklearn import datasets # to get dataset stored in sklearn

# suppressing warnings
import warnings
warnings.filterwarnings('ignore')

**Part 3: Loading (Rading) the Dataset**

In [3]:
# let's get the iris dataset stored in sklearn library
from sklearn.datasets import load_iris

In [4]:
iris_data = load_iris(as_frame=True)

# saving the iris dataset as df
df = iris_data.frame

**Part 4: EDA (Exploratory Data Analysis)**

**Steps in EDA:**

Basic Data Exploration (Examining the data attributes)
**Complete the following terms (homework):**

shape: displays the total number of rows and columns in a dataset.
size
ndim
columns
dtypes
Exploring more information about the dataset
Data cleaning
Feature engineering
Examining the missing values
Examining the outliers
Data visualization
Data mining

In [5]:
# creating a copy of df and name it iris
iris = df.copy()

In [6]:
# let's view the first 5 rows of the iris dataset
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [7]:
# let's view the last 5 rows of the iris dataset
iris.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [8]:
# shape
iris.shape

(150, 5)

In [9]:
iris.size

750

In [10]:
iris.ndim

2

In [11]:
iris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [12]:
iris.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
dtype: object

**Observation - 1:**

Add 5 points here as your observations from the obove outputs.

In [13]:
 # let's get more information about the dataset
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [14]:
# let's check for missing values
iris.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [15]:
# let's examine the statistical summary of the dataset
iris.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

**Observation - 3:**

Add 2 points here.

**Conclusion:**
1. I learned about colab in this lab that how it works.
2.We learned to measure statistical data about iris petals and sepals.
3. I learned how to enter text in colab and how to make headings bold.
4. I learned how to run code in colab.
5. i learned how to setup and navigate in google colab environment from scratch.
6. I learned how to link my school account with google colab.
7. I learned about python liabraries and pre written code packages and i learned how to import libraries.
8. I learned about loading the required dataset in our file.
9. I learned about statistical data such as size, shape and ndim measurement commands of a data set.
10. I learned about statistical summary of dataset how to analyze it.
11. In this lab we are basically dealing with a data related to a flower named iris and we are measuring it's sepals and petals dimensions.
12. we did examination of data attributes in this lab.